# -*- mode: ruby -*-
# vi: set ft=ruby :
# VM_BOX = "bento/ubuntu-22.04"
VM_BOX = "debian/bullseye64"
VM_IP = '10.0.0.30'
VM_HOSTNAME = 'debian'
LOCAL_SHARED_FOLDER = 'E:\virtual_machine\shared_folder'
LOCAL_SSH_PRI_KEY = File.readlines('C:\Users\joe\.ssh\id_rsa').first.strip
LOCAL_SSH_PUB_KEY = File.readlines('C:\Users\joe\.ssh\id_rsa.pub').first.strip


Vagrant.configure(2) do |config|
  config.vm.box = VM_BOX
  config.vm.disk :disk, size: "40GB", primary: true # export VAGRANT_EXPERIMENTAL="disks"
  config.vm.hostname = VM_HOSTNAME
  config.vm.network "private_network", ip: VM_IP
  config.vm.synced_folder LOCAL_SHARED_FOLDER, "/root/shared"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "8192"
    vb.cpus = 8
  end

  # Add Local SSH public key to the virtual machine
  config.vm.provision "shell", inline: <<-SHELL
    if [ ! -d "/home/vagrant/.ssh/" ]; then
      mkdir -p /home/vagrant/.ssh/
    fi
    if [ ! -d "/root/.ssh/" ]; then
      mkdir -p /root/.ssh/
    fi
    echo #{LOCAL_SSH_PRI_KEY} >> /root/.ssh/id_rsa
    echo #{LOCAL_SSH_PUB_KEY} >> /root/.ssh/id_rsa.pub
    echo #{LOCAL_SSH_PUB_KEY} >> /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/id_rsa*
  SHELL

  # system provisioning
  config.vm.provision :shell, path: '../scripts/bootstrap_debian.sh', keep_color: true
  # install python
  config.vm.provision :shell, path: '../scripts/install_python.sh', keep_color: true
  # install nodejs
  config.vm.provision :shell, path: '../scripts/install_nodejs.sh', keep_color: true
  # install docker
  config.vm.provision :shell, path: '../scripts/install_docker.sh', keep_color: true

end
